@baseUrl = http://localhost:3000/api

# @name createSkiCourseRegistration
POST {{baseUrl}}/course-registrations
Content-Type: application/json

{
    "firstName": "Chris",
    "lastName": "Flanky",
    "sportType": "Snowboard",
    "email": "cr.oss@example.com",
    "phone": "98765412",
    "age": "18",
    "additionalText": "Allergisch gegen Nüsse",
    "level": "Anfänger"
}

###

# @name getSkiCourseRegistrations
GET {{baseUrl}}/course-registrations

###

# @name getSkiCourseRegistrationById
GET {{baseUrl}}/course-registrations/{{createSkiCourseRegistration.response.body.data.id}}

###

# @name updateSkiCourseRegistration
PUT {{baseUrl}}/course-registrations/{{createSkiCourseRegistration.response.body.data.id}}
Content-Type: application/json

{
    "level": "Fortgeschritten"
}

###

# @name deleteSkiCourseRegistration
DELETE {{baseUrl}}/course-registrations/{{createSkiCourseRegistration.response.body.data.id}}
