# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: '$(FTP_SERVER)'
    username: '$(FTP_USER)'
    password: '$(FTP_USER_PW)'
    rootDirectory: '$(FTP_DIR_DIST)'
    filePatterns: '**'
    remoteDirectory: '$(FTP_DIR_DIST)'
    clean: false
    cleanContents: false
    preservePaths: false
    trustSSL: false
