@baseUrl = localhost:3000
@serverIp = localhost:3000

@serverName = localhost:3000

### E-Mail über die API senden (local)
POST http://{{baseUrl}}/send_email
Content-Type: application/json

{
    "recipientEmail": "test",
    "subject": "TEST",
    "body": "!!! TEST !!! "
}


### E-Mail über die API senden (AZURE VM)
POST https://{{serverIp}}/send_email
Content-Type: application/json

{
    "recipientEmail": "test",
    "subject": "TEST",
    "body": "!!! TEST !!! "
}

### E-Mail über die API senden (AZURE VM)
POST https://{{serverName}}/send_email
Content-Type: application/json

{
    "recipientEmail": "test",
    "subject": "TEST",
    "body": "!!! TEST !!! "
}
