@baseUrl = localhost:3000
@serverIp = localhost:3000

@serverName = localhost:3000

### E-Mail über die API senden (local -> http)
POST http://{{baseUrl}}/send_email
Content-Type: application/json

{
    "to": "test@test.com",
    "subject": "TEST",
    "text": "!!! TEST !!! "
}


### E-Mail über die API senden (AZURE VM -> https)
POST https://{{serverIp}}/send_email
Content-Type: application/json

{
    "to": "test@test.com",
    "subject": "TEST",
    "text": "!!! TEST !!! "
}

### E-Mail über die API senden (AZURE VM -> https)
POST https://{{serverName}}/send_email
Content-Type: application/json

{
    "to": "test@test.com",
    "subject": "TEST",
    "text": "!!! TEST !!! "
}
