# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include: 
    - '*'

variables:
- name: FTP_DIST_PATH
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    value: '$(FTP_DIR_DIST)'
  ${{ else }}:
    vlue '$(FTP_DIR_DIST_STAGE)'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: '$(FTP_SERVER)'
    username: '$(FTP_USER)'
    password: '$(FTP_USER_PW)'
    rootDirectory: '${{ variables.FTP_DIST_PATH }}'
    filePatterns: '**'
    remoteDirectory: '${{ variables.FTP_DIST_PATH }}'
    clean: false
    cleanContents: false
    preservePaths: false
    trustSSL: false
