@baseUrl = localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJuZXVlckJlbnV0emVyIiwiaWF0IjoxNzMwNjUxMTYwLCJleHAiOjE3MzA2NTQ3NjB9.RKPOT_o3r63P9aFec_pEQkgH4WCyTM3Y6q4ZwMlc0SY

### Registrierung eines neuen Benutzers
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "username": "neuerBenutzer",
  "password": "meinPasswort123"
}

### Benutzer-Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "neuerBenutzer",
  "password": "meinPasswort123"
}

### Erhalte alle Items (erfordert Token)
# Ersetze <TOKEN> durch den tatsächlich erhaltenen Token aus dem Login-Endpunkt
GET http://localhost:3000/api/items
Authorization: Bearer {{token}}

### Erhalte ein spezifisches Item (z.B. Item mit ID 1, erfordert Token)
GET http://localhost:3000/api/items/1
Authorization: Bearer {{token}}

### Erstelle ein neues Item (erfordert Token)
POST http://localhost:3000/api/items
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Neues Item"
}

### Aktualisiere ein Item (z.B. Item mit ID 1, erfordert Token)
PUT http://localhost:3000/api/items/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "PENISSSS!!!!"
}

### Lösche ein Item (z.B. Item mit ID 1, erfordert Token)
DELETE http://localhost:3000/api/items/2
Authorization: Bearer {{token}}
