# .github/workflows/sck-api-build.yml
name: SCK-API Build

on:
  push:
    branches:
      - "**"  # Alle Branches
    paths:
      - "src/api/sck-api/**/*"
      - ".github/workflows/sck-api-*"

env:
  PROJECT_PATH: "src/api/sck-api/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # PREPARE
      - name: Install dependencies
        run: |
          cd ${{ env.PROJECT_PATH }}
          npm ci

      # # QA
      # - name: Run linting and tests
      #   run: |
      #     cd ${{ env.PROJECT_PATH }}
      #     npm run test

      # BUILD
      - name: Build project
        run: |
          cd ${{ env.PROJECT_PATH }}
          npm run build

      # Build-Artefakte für Deployment bereitstellen
      - name: Upload build artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: sck-api-build
          path: ${{ env.PROJECT_PATH }}dist/
          retention-days: 1
