name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - "master"
    paths:
      # - "src/ui/sck-web/*"
      - "src/web/*"
      - ".github/workflows/sck-web-app-*"

env:
  PROJECT_PATH: "src/web/"
  APACHE_HTACCESS_SCK_APP: "src/web/projects/sck-app/src/.htaccess"
  PROJECT_DIST_PATH: "src/web/dist/sck-app/"

  COURSE_SHEET_URL: ${{ secrets.COURSE_SHEET_URL }}
  TRIP_SHEET_URL: ${{ secrets.TRIP_SHEET_URL }}
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # ENV SUBSTITUTION
      - name: Environment substitution
        run: |
          cd ${{ env.PROJECT_PATH }}/scripts
          ./envsubst.sh "${{ secrets.COURSE_SHEET_URL }}" "${{ secrets.TRIP_SHEET_URL }}"

      # Install dependencies and build project
      - name: Install dependencies and build project
        run: |
          cd ${{ env.PROJECT_PATH }}
          npm install -g @angular/cli
          npm install
          npm run build

      # Copy .htaccess for Apache WebServer
      - name: Copy .htaccess file
        run: |
          cp ${{ env.APACHE_HTACCESS_SCK_APP }} ${{ env.PROJECT_DIST_PATH }}

      # Install sshpass
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # Secure copy files to remote server
      - name: SCP files to server
        run: |
          cd ${{ env.PROJECT_DIST_PATH }}
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o "StrictHostKeyChecking=no" -r . ${{ secrets.SSH_USER }}@${{ secrets.SERVER_ADDRESS }}:${{ env.SERVER_DIST_PATH }}
        env:
          SERVER_DIST_PATH: ${{ github.ref == 'refs/heads/master' && secrets.SERVER_DIST_PATH_BASE || secrets.SERVER_DIST_PATH_STAGE }}

  # Optional: FTP upload (if needed, uncomment this section)
  # ftp_upload:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #   - name: FTP Upload
  #     uses: sebastianpopp/ftp-action@v2
  #     with:
  #       host: ${{ secrets.SERVER_ADDRESS }}
  #       username: ${{ secrets.SSH_USER }}
  #       password: ${{ secrets.SSH_PASSWORD }}
  #       local-dir: ${{ env.PROJECT_DIST_PATH }}
  #       remote-dir: ${{ env.SERVER_DIST_PATH }}
  #       trust-ssl: true
